import type { SiteContent } from "./types";

const en: SiteContent = {
  nav: {
    heading: "Menu",
    items: [
      { id: "hero", label: "Home" },
      { id: "countdown", label: "Countdown" },
      { id: "our-story", label: "Our Story" },
      { id: "itinerary", label: "Itinerary" },
      { id: "info", label: "Locations" },
      { id: "dresscode", label: "Dress Code" },
      { id: "registry", label: "Gift Registry" },
      { id: "rsvp", label: "RSVP" },
      { id: "faq", label: "FAQ" },
    ],
  },
  hero: {
    scroll: "See more",
  },
  countdown: {
    heading: "Countdown",
    labels: {
      months: "Months",
      days: "Days",
      hours: "Hours",
      minutes: "Minutes",
      seconds: "Seconds",
    },
  },
  photoCarousel: {
    heading: "Our Moments",
    photos: [
      { imagePath: "/images/carru1.jpg", alt: "Photo of Sol and Gabriel 1", orientation: "landscape" },
      { imagePath: "/images/carru2.jpg", alt: "Photo of Sol and Gabriel 2", orientation: "landscape" },
      { imagePath: "/images/carru3b.jpg", alt: "Photo of Sol and Gabriel 3", orientation: "landscape" },
      { imagePath: "/images/carru4.jpg", alt: "Photo of Sol and Gabriel 4", orientation: "landscape" },
      { imagePath: "/images/carru5b.jpg", alt: "Photo of Sol and Gabriel 5", orientation: "landscape" },
      { imagePath: "/images/carru6b.jpg", alt: "Photo of Sol and Gabriel 6", orientation: "landscape" },
    ],
  },
  eventInfo: {
    heading: "Locations",
    flipLabel: "See more",
    openInMaps: "Open in Maps",
    events: [
      {
        name: "Ceremony",
        imagePath: "/images/fatima_fondo.png",
        time: "11:45 AM",
        address: "Parroquia Nuestra Señora de Fátima · Av. Armendariz 350, Miraflores",
        mapsUrl: "https://maps.app.goo.gl/UqyHfwYS5m7971fz5",
      },
      {
        name: "Reception",
        imagePath: "/images/lilas_medio_rosado.png",
        time: "3:00 PM",
        address: "Hacienda Las Lilas · Pachacamac",
        mapsUrl: "https://maps.app.goo.gl/HqxFEcde4zyGsXae6"
      },
    ],
  },
  ourStory: {
    eyebrow: "You are cordially invited to this adventure called...",
    heading: "Our Love Story",
    milestones: [
      {
        title: "University",
        text: "We met in our first semester of university and became close friends right away. Since we were in different majors, a few semesters later we no longer shared classes, but we still went out for lunch after class or took advantage of sushi combo deals.",
        photos: [
          { imagePath: "/images/IMG_1981.jpg", alt: "In a classroom at UP", orientation: "portrait" },
          { imagePath: "/images/nori.jpg", alt: "Sol and Gabriel when they met", orientation: "portrait", caption: "A sushi combo deal" },
        ],
      },
      {
        title: "New Year's 2020",
        text: "S: After seeing each other more often again over sushi, I invited him to spend New Year's at the beach with some coworkers. Everyone could see the chemistry between us except us — but their comments planted the idea that we might make a good couple.",
        photos: [
          { imagePath: "/images/IMG_8479.jpg", alt: "Gabriel, Sol, and the sun", orientation: "landscape" },
          { imagePath: "/images/IMG_8384.jpg", alt: "A jumping pose, two friends", orientation: "portrait" },
          { imagePath: "/images/IMG_8463.jpg", alt: "The first piggyback ride", orientation: "portrait" },
        ],
      },
      {
        title: "Together",
        text: "S: After a summer of more dates and movie marathons, Gabriel decided to ask me to be his girlfriend — picking up my dad's guitar and singing me a Cultura Profética song: 'Me faltabas tú' (I was missing you).",
        photos: [
          { imagePath: "/images/IMG_0104.jpg", alt: "San Bartolo", orientation: "portrait" },
          { imagePath: "/images/IMG_0950.jpg", alt: "Close to our first anniversary", orientation: "landscape" },
        ],
      },
      {
        title: "Promise",
        text: "G: Over the years we grew, graduated, traveled, started working, and grew closer. On our 3rd anniversary, I gave Sol a ring with the promise that in a few years I'd trade it for an engagement ring.",
        photos: [
          { imagePath: "/images/IMG_6012.jpg", alt: "Her and her sunflowers", orientation: "portrait" },
          { imagePath: "/images/IMG_8283.jpg", alt: "The promise ring", orientation: "landscape" },
          { imagePath: "/images/IMG_0608.JPG", alt: "A heart on the beach", orientation: "portrait" },
          { imagePath: "/images/IMG_5975.jpg", alt: "The Uyuni salt flats", orientation: "landscape" },
          { imagePath: "/images/IMG_7927.jpg", alt: "'We made it!'", orientation: "portrait" },
        ],
      },
      {
        title: "Engaged",
        text: "G: On a getaway to Cartagena, in the Rosario Islands archipelago, I planned an intimate proposal for Sol. And so, after years and years of pleading...",
        highlight: "She said yes!",
        photos: [],
      },
    ],
  },
  photoCollage: {
    photos: [
      { imagePath: "", alt: "Photo of Sol and Gabriel 1", orientation: "portrait" },
      { imagePath: "", alt: "Photo of Sol and Gabriel 2", orientation: "landscape" },
      { imagePath: "", alt: "Photo of Sol and Gabriel 3", orientation: "portrait" },
      { imagePath: "", alt: "Photo of Sol and Gabriel 4", orientation: "landscape" },
      { imagePath: "", alt: "Photo of Sol and Gabriel 5", orientation: "portrait" },
      { imagePath: "", alt: "Photo of Sol and Gabriel 6", orientation: "portrait" },
      { imagePath: "", alt: "Photo of Sol and Gabriel 7", orientation: "landscape" },
      { imagePath: "", alt: "Photo of Sol and Gabriel 8", orientation: "portrait" },
      { imagePath: "", alt: "Photo of Sol and Gabriel 9", orientation: "portrait" },
      { imagePath: "", alt: "Photo of Sol and Gabriel 10", orientation: "landscape" },
    ],
  },
  itinerary: {
    heading: "Itinerary",
    items: [
      { time: "11:45 AM", name: "Mass", imagePath: "/images/dib_misa.png" },
      { time: "3:00 PM", name: "Reception", imagePath: "/images/dib_recepcion.png" },
      { time: "5:30 PM", name: "Dinner", imagePath: "/images/dib_cena.png" },
      { time: "6:30 PM", name: "Party", imagePath: "/images/dib_fiesta.png" },
    ],
  },
  featuredPhoto: {
    photos: [
      { imagePath: "/images/carruB2.jpg", alt: "Photo of Sol and Gabriel" },
    ],
  },
  featuredPhoto2: {
    photos: [{ imagePath: "/images/carruB7.jpg", alt: "Photo of Sol and Gabriel" }],
  },
  featuredPhoto3: {
    photos: [{ imagePath: "/images/carruB8.jpg", alt: "Photo of Sol and Gabriel" }],
  },
  featuredPhoto4: {
    photos: [{ imagePath: "/images/anillo_manos.jpg", alt: "Photo of Sol and Gabriel" }],
  },
  dressCode: {
    heading: "Dress Code",
    style: "Elegant",
    lines: [
      "Gentlemen: suit and tie.",
      "Ladies: long dress or cocktail dress.",
      "Please avoid white, ivory, beige, and cream, as these colors are reserved for the bride.",
    ],
  },
  registry: {
    heading: "Gift Registry",
    intro: "Thank you for thinking of a gift for us!",
    lines: [
      "Your presence is the best gift of all.",
      "If you'd like to give us something, we've put together a small list of things for our new home. Whatever you choose will reach us instantly.",
    ],
    buyLabel: "Choose gift",
    freeContributionLabel: "Open contribution",
    customAmountPrompt: "Amount in S/",
    showAllLabel: "Show all gifts",
    showLessLabel: "Show less",
    purchaseSuccess: "Thank you! Your gift was processed successfully.",
    purchaseError: "We couldn't process your payment right now. Please try again in a few minutes, or use the bank transfer option instead.",
    addToCartLabel: "Add",
    inCartLabel: "Added ✓",
    checkoutLabel: "Pay for gifts",
    cartSummaryLabel: "gifts selected",
    totalLabel: "Total:",
    cartDrawerHeading: "Cart",
    securePaymentHeading: "Secure payment with Culqi",
    securePaymentNote: "By continuing, a secure Culqi window will open to complete your payment. Your card details are protected and never pass through this website.",
    buyerNamePlaceholder: "Buyer's name",
    buyerEmailPlaceholder: "Email",
    buyerPhonePlaceholder: "Phone",
    dedicationPlaceholder: "Message (optional)",
    goToPayLabel: "Go to payment",
    processingLabel: "Processing payment...",
    removeLabel: "Remove",
    products: [
      {
        imagePath: "/images/playa_italia.jpg",
        category: "honeymoon",
        name: "Open contribution - Honeymoon",
        description: "An open contribution toward our honeymoon and the first memories of this new chapter.",
        price: null,
      },
      {
        imagePath: "/images/princeton.jpg",
        category: "graduate studies",
        name: "Open contribution - Graduate studies",
        description: "An open contribution to help us get closer to our dream graduate programs and keep growing together.",
        price: null,
      },
      {
        imagePath: "/images/moje_mis_sabanas_blancas.webp",
        category: "home",
        name: "Cotton bedsheet set",
        description: "A bedsheet set to make our rest more comfortable.",
        price: 450,
      },
      {
        imagePath: "/images/tabla_quesos.png",
        category: "kitchen",
        name: "Cheese board set",
        description: "A cheese board, perfect for sharing and celebrating special moments together.",
        price: 200,
      },
      {
        imagePath: "/images/copas.webp",
        category: "kitchen",
        name: "Wine glasses",
        description: "Wine glasses, the perfect companion for good conversation.",
        price: 300,
      },
      {
        imagePath: "/images/bar_set.jpg",
        category: "kitchen",
        name: "Professional bar set",
        description: "A complete set for making cocktails at home, perfect for nights hosting friends.",
        price: 210,
      },
      {
        imagePath: "/images/joycon.jpg",
        category: "home",
        name: "Joy-Con controllers",
        description: "For our game nights together or with friends who come to visit.",
        price: 390,
      },
      {
        imagePath: "/images/hielera.jpg",
        category: "kitchen",
        name: "Stainless steel ice bucket",
        description: "A stylish ice bucket so our get-togethers at home always have something cold on hand.",
        price: 170,
      },
      {
        imagePath: "/images/cubrecama.jpg",
        category: "home",
        name: "Cotton bedspread",
        description: "A cozy bedspread for quiet weekend mornings at home.",
        price: 260,
      },
      {
        imagePath: "/images/edredon.webp",
        category: "home",
        name: "Comforter",
        description: "A comforter to make our rest together even more comfortable.",
        price: 300,
      },
      {
        imagePath: "/images/freidora_aire.jpg",
        category: "kitchen",
        name: "Air fryer",
        description: "To encourage us to cook new recipes together and share dinner at home.",
        price: 400,
      },
      {
        imagePath: "/images/parlante_bose.jpg",
        category: "home",
        name: "Bluetooth speaker",
        description: "Good music to accompany our evenings at home and gatherings with friends.",
        price: 1500,
      },
      {
        imagePath: "/images/puf.jpg",
        category: "home",
        name: "Decorative pouf",
        description: "One more cozy corner for our living room, perfect for guests and long conversations.",
        price: 150,
      },
      {
        imagePath: "/images/cubiertos.jpg",
        category: "kitchen",
        name: "Cutlery set",
        description: "Cutlery for the family and friend dinners we look forward to sharing in our new home.",
        price: 200,
      },
      {
        imagePath: "/images/vajilla.jpg",
        category: "kitchen",
        name: "Porcelain dinnerware set",
        description: "Dinnerware to welcome the people we love and celebrate every special occasion together.",
        price: 360,
      },
      {
        imagePath: "/images/mueble_bar.jpg",
        category: "home",
        name: "Bar cabinet",
        description: "A special corner to prepare and share a good drink, whether just the two of us or with friends visiting.",
        price: 2600,
      },
      {
        imagePath: "/images/mesa_centro.jpg",
        category: "home",
        name: "Coffee table",
        description: "The gathering point of our living room, for coffee afternoons together or hangouts with friends.",
        price: 2050,
      },
      {
        imagePath: "/images/difusor_aromatico.jpg",
        category: "home",
        name: "Aroma diffuser",
        description: "A warm, welcoming scent so our home always feels like a good refuge.",
        price: 330,
      },
      {
        imagePath: "/images/olla_gourmet.jpg",
        category: "kitchen",
        name: "Gourmet pot",
        description: "To encourage us to cook together and share our favorite dishes at home.",
        price: 190,
      },
      {
        imagePath: "/images/batidora_kitchenaid.jpg",
        category: "kitchen",
        name: "Stand mixer",
        description: "A stand mixer to encourage us to bake together and share homemade desserts with the people we love.",
        price: 1450,
      },
    ],
    bankTransfer: {
      heading: "Prefer to do it by bank transfer?",
      note: [
        "If you'd prefer to send a transfer, you can use the following accounts under the name Gabriel Dejo.",
        "Please include your name in the transfer note so we can thank you for your gift."
      ],
      accounts: [
        {
          bank: "BCP",
          accountNumber: "19170142836048",
          cci: "00219117014283604853",
        },
        {
          bank: "Scotiabank",
          accountNumber: "8330064602",
          cci: "00972420833006460267",
        },
        {
          bank: "Interbank",
          accountNumber: "1003276288960",
          cci: "00310001327628896059",
        },
      ],
    },
    legalLinks: [
      { label: "Merchant details", href: "/datos-del-comercio" },
      { label: "Terms & conditions", href: "/terminos-y-condiciones" },
      { label: "Returns & exchanges", href: "/politica-cambios-devoluciones" },
      { label: "Complaints book", href: "/libro-de-reclamaciones" },
    ],
  },
  rsvp: {
    heading: "Confirm Attendance",
    subtitle: "RSVP",
    deadline: "Please confirm by October 8",
    namePlaceholder: "First and last name",
    emailPlaceholder: "Email address",
    willYouAttend: "Will you attend?",
    accepts: "Joyfully accepts",
    declines: "Regretfully declines",
    numberOfGuests: "Number of guests",
    notesPlaceholder: "Message for the couple (optional)",
    submit: "Confirm attendance",
    thankYou: "Thank you!",
    thankYouMessage: "We've received your confirmation. We can't wait to celebrate together!",
    submitError: "We couldn't submit your confirmation. Please try again.",
    guestNotFound: "We couldn't find your name on the guest list. If you think this is a mistake, please contact us.",
  },
  faq: {
    heading: "Frequently Asked Questions",
    items: [
      {
        question: "What time should I arrive for the ceremony and reception?",
        answer: "For the ceremony, please arrive between 11:40 and 11:50 a.m. so you have enough time to be seated before it begins promptly at 12:00 p.m.\nFor the reception, please arrive between 3:00 and 3:15 p.m. to get settled before the civil ceremony and vows, which will begin at 3:30 p.m.",
      },
      {
        question: "How do I confirm my attendance?",
        answer: "You can confirm your attendance in the 'Confirm Attendance' section or by messaging us on WhatsApp.\n We'd appreciate confirming by October 8. If we don't receive your confirmation by that date, we'll understand that you unfortunately won't be able to join us that day.",
      },
      {
        question: "Is this an adults-only event?",
        answer: "Yes, with much love we ask that this celebration be adults only.",
      },
      {
        question: "Will there be parking?",
        answer: "Yes, both venues have parking available for guests. For the church, there's an Apparka lot on the same block, at Av. Armendáriz 350.",
      },
      {
        question: "How does the gift registry work?",
        answer: "You can choose one of the gifts we've selected or, if you prefer, make an open contribution that we'll lovingly put toward our honeymoon. Once you choose a gift, the site will take you to a secure platform where you can complete the payment with a credit card, debit card, Yape, or Plin.\n\nIf you'd prefer to do it by bank transfer, you can use the following accounts under the name Gabriel Dejo.\n BCP\n19170142836048\nCCI 00219117014283604853\n\nScotiabank\n8330064602\nCCI 00972420833006460267\n\nInterbank\n1003276288960\nCCI 00310001327628896059\n\nPlease include your name in the transfer note so we can thank you for your gift.",
      },
    ],
  },
  contact: {
    heading: "Have any questions?",
    lines: [
      "We're happy to help with any questions about the event.",
      "Message us directly on WhatsApp.",
    ],
    whatsappLabel: "Message us",
    whatsappUrl: "https://wa.me/34600000000?text=Hi%20Sol%20%26%20Gabriel!",
  },
  merchant: {
    tradeName: "Sol & Gabriel Gift Registry",
    legalName: "DEJO SEMINARIO GABRIEL FERNANDO",
    taxId: "10729321767",
    phone: "948427924",
    email: "gabrieldejos@gmail.com",
    address: "Jirón Aragón 119, Lima, Peru",
  },
};

export default en;
