import type { SiteContent } from "./types";

const es: SiteContent = {
  nav: {
    heading: "Menú",
    items: [
      { id: "hero", label: "Inicio" },
      { id: "countdown", label: "Cuenta regresiva" },
      { id: "our-story", label: "Nuestra historia" },
      { id: "itinerary", label: "Itinerario" },
      { id: "info", label: "Locaciones" },
      { id: "dresscode", label: "Código de vestimenta" },
      { id: "registry", label: "Mesa de regalos" },
      { id: "rsvp", label: "Confirmar asistencia" },
      { id: "faq", label: "Preguntas frecuentes" },
    ],
  },
  hero: {
    scroll: "Ver más",
  },
  countdown: {
    heading: "Cuenta regresiva",
    labels: {
      months: "Meses",
      days: "Días",
      hours: "Horas",
      minutes: "Minutos",
      seconds: "Segundos",
    },
  },
  photoCarousel: {
    heading: "Nuestros Momentos",
    photos: [
      { imagePath: "/images/carru1.jpg", alt: "Foto de Sol y Gabriel 1", orientation: "landscape" },
      { imagePath: "/images/carru2.jpg", alt: "Foto de Sol y Gabriel 2", orientation: "landscape" },
      { imagePath: "/images/carru3.jpg", alt: "Foto de Sol y Gabriel 3", orientation: "landscape" },
      { imagePath: "/images/carru4.jpg", alt: "Foto de Sol y Gabriel 4", orientation: "landscape" },
      { imagePath: "/images/carru5b.jpg", alt: "Foto de Sol y Gabriel 5", orientation: "landscape" },
      { imagePath: "/images/carru6b.jpg", alt: "Foto de Sol y Gabriel 6", orientation: "landscape" },
    ],
  },
  eventInfo: {
    heading: "Locaciones",
    flipLabel: "Ver más",
    openInMaps: "Abrir en Maps",
    events: [
      {
        name: "Iglesia",
        imagePath: "/images/fatima_fondo.png",
        time: "12:00 M",
        address: "Parroquia Nuestra Señora de Fátima · Av. Armendariz 350, Miraflores",
        mapsUrl: "https://maps.app.goo.gl/UqyHfwYS5m7971fz5",
      },
      {
        name: "Hacienda",
        imagePath: "/images/lilas_medio_rosado.png",
        time: "3:30 PM",
        address: "Hacienda Las Lilas · Pachacamac",
        mapsUrl: "https://maps.app.goo.gl/HqxFEcde4zyGsXae6"
      },
    ],
  },
  ourStory: {
    eyebrow: "Estás cordialmente invitado a esta aventura llamada...",
    heading: "Nuestra historia de Amor",
    milestones: [
      {
        title: "Universidad",
        text: "Nos conocimos en el primer ciclo de la universidad y nos hicimos muy amigos al instante. Por ser de diferentes carreras, ciclos después ya no coincidíamos en los cursos, pero aún salíamos para almorzar después de clases o aprovechar promos de Makis.",
        photos: [
          { imagePath: "/images/IMG_1981.jpg", alt: "En un salón de la UP", orientation: "portrait" },
          { imagePath: "/images/nori.jpg", alt: "Sol y Gabriel al conocerse", orientation: "portrait", caption: "Una promo de makis" },
          //{ imagePath: "", alt: "Sol y Gabriel en sus primeros meses", orientation: "landscape" },
        ],
      },
      {
        title: "Año Nuevo 2020",
        text: " Después de vernos más seguido otra vez por los Makis, lo invité a pasar Año Nuevo en la playa junto con otros amigos de la chamba. Todos podían ver la buena química que teníamos, menos nosotros, pero sus palabras nos dejaron esa idea de que podríamos ser buena pareja.",
        photos: [
          { imagePath: "/images/IMG_8479.jpg", alt: "Gabriel, Sol y el sol", orientation: "landscape" },
          { imagePath: "/images/IMG_8384.jpg", alt: "Una pose saltando, de dos amigos", orientation: "portrait" },
          { imagePath: "/images/IMG_8463.jpg", alt: "La primera cargada", orientation: "portrait" },
        ],
      },
      {
        title: "Enamorados",
        text: "Después de un verano con más salidas y maratones de películas, Gabriel decidió pedirme ser su enamorada, agarrando la guitarra de mi papá, y cantándome una canción de Cultura Profética: Me faltabas tú",
        photos: [
          { imagePath: "/images/IMG_0104.jpg", alt: "San Bartolo", orientation: "portrait" },
          { imagePath: "/images/IMG_0950.jpg", alt: "Cerca a nuestro primer aniversario", orientation: "landscape" },
        ],
      },
      {
        title: "Promesa",
        text: "A lo largo de los años crecimos, nos graduamos, viajamos, empezamos a trabajar y nos unimos más. Al cumplir nuestro aniversario #3, le regalé a Sol un anillo con la promesa de que en algunos años lo cambiaría por uno de compromiso.",
        photos: [
          { imagePath: "/images/IMG_6012.jpg", alt: "Ella y sus girasoles", orientation: "portrait" },
          { imagePath: "/images/IMG_8283.jpg", alt: "El anillo de promesa", orientation: "landscape" },
          { imagePath: "/images/IMG_0608.JPG", alt: "Un corazón en la playa", orientation: "portrait" },
          { imagePath: "/images/IMG_5975.jpg", alt: "El salar de Uyuni", orientation: "landscape" },
          { imagePath: "/images/IMG_7927.jpg", alt: "'¡Sí se pudo, burro!'", orientation: "portrait" },
        ],
      },
      {
        title: "Comprometidos",
        text: "En un viaje de desconexión a Cartagena, en el archipiélago de las islas del Rosario, le preparé a Sol una pedida íntima. Así, después de años y años de súplicas...",
        highlight: "¡Me dijo que sí!",
        photos: [],
      },
    ],
  },
  photoCollage: {
    photos: [
      { imagePath: "", alt: "Foto de Sol y Gabriel 1", orientation: "portrait" },
      { imagePath: "", alt: "Foto de Sol y Gabriel 2", orientation: "landscape" },
      { imagePath: "", alt: "Foto de Sol y Gabriel 3", orientation: "portrait" },
      { imagePath: "", alt: "Foto de Sol y Gabriel 4", orientation: "landscape" },
      { imagePath: "", alt: "Foto de Sol y Gabriel 5", orientation: "portrait" },
      { imagePath: "", alt: "Foto de Sol y Gabriel 6", orientation: "portrait" },
      { imagePath: "", alt: "Foto de Sol y Gabriel 7", orientation: "landscape" },
      { imagePath: "", alt: "Foto de Sol y Gabriel 8", orientation: "portrait" },
      { imagePath: "", alt: "Foto de Sol y Gabriel 9", orientation: "portrait" },
      { imagePath: "", alt: "Foto de Sol y Gabriel 10", orientation: "landscape" },
    ],
  },
  itinerary: {
    heading: "Itinerario",
    items: [
      { time: "12:00 M", name: "Misa", imagePath: "/images/dib_misa.png" },
      { time: "3:00 PM", name: "Recepción", imagePath: "/images/dib_recepcion.png" },
      { time: "5:30 PM", name: "Cena", imagePath: "/images/dib_cena.png" },
      { time: "6:30 PM", name: "Fiesta", imagePath: "/images/dib_fiesta.png" },
    ],
  },
  featuredPhoto: {
    photos: [
      //{ imagePath: "/images/carruB1.jpg", alt: "Foto de Sol y Gabriel" },
      { imagePath: "/images/carruB2.jpg", alt: "Foto de Sol y Gabriel" },
    ],
  },
  featuredPhoto2: {
    photos: [{ imagePath: "/images/carruB7.jpg", alt: "Foto de Sol y Gabriel" }],
  },
  featuredPhoto3: {
    photos: [{ imagePath: "/images/carruB8.jpg", alt: "Foto de Sol y Gabriel" }],
  },
  featuredPhoto4: {
    photos: [{ imagePath: "/images/anillo_manos.jpg", alt: "Foto de Sol y Gabriel" }],
  },
  dressCode: {
    heading: "Código de Vestimenta",
    style: "Elegante",
    lines: [
      "Caballeros: terno y corbata.",
      "Damas: vestido largo o cóctel.",
      "Por favor, evitar el blanco, ivory, beige y marfil, ya que estarán reservados para la novia.",
    ],
  },
  registry: {
    heading: "Mesa de Regalos",
    intro: "¡Gracias por pensar en un detalle para nosotros!",
    lines: [
      "Tu presencia es el mejor regalo de todos.",
      "Si desean obsequiarnos algo, hemos preparado una pequeña lista de cosas para nuestro nuevo hogar. El detalle que elijan nos llegará a nosotros de forma instantánea.",
    ],
    buyLabel: "Elegir regalo",
    freeContributionLabel: "Aporte libre",
    customAmountPrompt: "Monto en S/",
    showAllLabel: "Ver todos los regalos",
    showLessLabel: "Ver menos",
    purchaseSuccess: "¡Gracias! Tu regalo se procesó correctamente.",
    purchaseError: "No pudimos procesar tu pago en este momento. Por favor, inténtalo nuevamente en unos minutos o, si lo prefieres, utiliza la opción de transferencia bancaria.",
    addToCartLabel: "Agregar",
    inCartLabel: "Agregado ✓",
    checkoutLabel: "Pagar regalos",
    cartSummaryLabel: "regalos seleccionados",
    totalLabel: "Total:",
    cartDrawerHeading: "Carrito",
    securePaymentHeading: "Pago seguro con Culqi",
    securePaymentNote: "Al continuar, se habilitará una ventana segura de Culqi para completar el pago. Los datos de tu tarjeta están protegidos y no pasan por esta web.",
    buyerNamePlaceholder: "Nombre del comprador",
    buyerEmailPlaceholder: "Correo",
    buyerPhonePlaceholder: "Teléfono",
    dedicationPlaceholder: "Dedicatoria (opcional)",
    goToPayLabel: "Ir a pagar",
    removeLabel: "Quitar",
    products: [
      {
        imagePath: "/images/playa_italia.jpg",
        category: "luna de miel",
        name: "Aporte libre - Luna de miel",
        description: "Un aporte libre para nuestra luna de miel y los primeros recuerdos de esta nueva etapa.",
        price: null,
      },
      {
        imagePath: "/images/princeton.jpg",
        category: "estudios",
        name: "Aporte libre - Maestrías",
        description: "Un aporte libre que nos acercará a nuestas maestrías soñadas y a seguir creciendo juntos.",
        price: null,
      },
      {
        imagePath: "/images/moje_mis_sabanas_blancas.webp",
        category: "hogar",
        name: "Juego de sábanas de algódon",
        description: "Juego de sábanas para hacer más cómodo nuestro descanso.",
        price: 450,
      },
      {
        imagePath: "/images/tabla_quesos.png",
        category: "cocina",
        name: "Set tabla de quesos",
        description: "Una tabla para quesos, ideal para compartir y celebrar momentos especiales juntos.",
        price: 200,
      },
      {
        imagePath: "/images/copas.webp",
        category: "cocina",
        name: "Copas de vino",
        description: "Copas de vino, el complemento perfecto para compartir una buena conversación.",
        price: 300,
      },
      {
        imagePath: "/images/bar_set.jpg",
        category: "cocina",
        name: "Set de bar profesional",
        description: "Un set completo para preparar tragos en casa, perfecto para las noches en las que recibimos amigos.",
        price: 210,
      },
      {
        imagePath: "/images/hielera.jpg",
        category: "cocina",
        name: "Hielera de acero inoxidable",
        description: "Una hielera con estilo para que las reuniones en casa siempre tengan algo bien frío a la mano.",
        price: 170,
      },
      {
        imagePath: "/images/cubrecama.jpg",
        category: "hogar",
        name: "Cubrecama de algodón",
        description: "Un cubrecama abrigador para esas mañanas tranquilas de fin de semana en nuestro hogar.",
        price: 260,
      },
      {
        imagePath: "/images/edredon.webp",
        category: "hogar",
        name: "Edredón de cama",
        description: "Un edredón para que nuestro descanso juntos sea aún más cómodo.",
        price: 300,
      },
      {
        imagePath: "/images/freidora_aire.jpg",
        category: "cocina",
        name: "Freidora de aire",
        description: "Para animarnos a cocinar juntos recetas nuevas y compartir la cena en casa.",
        price: 400,
      },
      {
        imagePath: "/images/parlante_bose.jpg",
        category: "hogar",
        name: "Parlante bluetooth",
        description: "Buena música para acompañar nuestras tardes en casa y las reuniones con amigos.",
        price: 1500,
      },
      {
        imagePath: "/images/puf.jpg",
        category: "hogar",
        name: "Puf decorativo",
        description: "Un rincón cómodo de más para nuestra sala, ideal para las visitas y las tardes de conversación.",
        price: 150,
      },
      {
        imagePath: "/images/cubiertos.jpg",
        category: "cocina",
        name: "Juego de cubiertos",
        description: "Cubiertos para las cenas en familia y con amigos que esperamos compartir en nuestro nuevo hogar.",
        price: 200,
      },
      {
        imagePath: "/images/vajilla.jpg",
        category: "cocina",
        name: "Juego de vajilla de porcelana",
        description: "Una vajilla para recibir a quienes queremos y celebrar juntos cada ocasión especial.",
        price: 360,
      },
      {
        imagePath: "/images/mueble_bar.jpg",
        category: "hogar",
        name: "Mueble bar",
        description: "Un rincón especial para preparar y compartir un buen trago, ya sea en pareja o con amigos de visita.",
        price: 2600,
      },
      {
        imagePath: "/images/mesa_centro.jpg",
        category: "hogar",
        name: "Mesa de centro",
        description: "El punto de encuentro de nuestra sala, para tardes de café en pareja o reuniones con amigos.",
        price: 2050,
      },
      {
        imagePath: "/images/difusor_aromatico.jpg",
        category: "hogar",
        name: "Difusor aromático",
        description: "Un aroma cálido y acogedor para que nuestro hogar se sienta siempre como un buen refugio.",
        price: 330,
      },
      {
        imagePath: "/images/olla_gourmet.jpg",
        category: "cocina",
        name: "Olla gourmet",
        description: "Para animarnos a cocinar juntos y compartir en casa nuestros platos favoritos.",
        price: 190,
      },
      {
        imagePath: "/images/batidora_kitchenaid.jpg",
        category: "cocina",
        name: "Batidora",
        description: "Una batidora para animarnos a hornear juntos y compartir postres caseros con quienes queremos.",
        price: 1450,
      },
    ],
    bankTransfer: {
      heading: "¿Prefieres hacerlo por transferencia?",
      note: [
        "Si prefieren hacerlo mediante transferencia, pueden realizarlo a las siguientes cuentas a nombre de Gabriel Dejo.",
        "Les agradeceremos puedan colocar su nombre en el concepto para poder agradecerles por su detalle."
      ],
      accounts: [
        {
          bank: "BCP",
          accountNumber: "19170142836048",
          cci: "00219117014283604853",
        },
        {
          bank: "Scotiabank",
          accountNumber: "833-0064602",
          cci: "00972420833006460267",
        },
        {
          bank: "Interbank",
          accountNumber: "100-3276288960",
          cci: "00310001327628896059",
        },
      ],
    },
    legalLinks: [
      { label: "Datos del comercio", href: "/datos-del-comercio" },
      { label: "Términos y condiciones", href: "/terminos-y-condiciones" },
      { label: "Cambios y devoluciones", href: "/politica-cambios-devoluciones" },
      { label: "Libro de reclamaciones", href: "/libro-de-reclamaciones" },
    ],
  },
  rsvp: {
    heading: "Confirmar Asistencia",
    subtitle: "RSVP",
    deadline: "Por favor confirmar antes del 8 de octubre",
    namePlaceholder: "Nombre y apellido",
    emailPlaceholder: "Correo electrónico",
    willYouAttend: "¿Asistirás?",
    accepts: "Con gusto asistirá",
    declines: "Con pena no podrá",
    numberOfGuests: "Número de acompañantes",
    notesPlaceholder: "Mensaje para los novios (opcional)",
    submit: "Confirmar asistencia",
    thankYou: "¡Gracias!",
    thankYouMessage: "Hemos recibido tu confirmación. ¡No podemos esperar para celebrar juntos!",
    submitError: "No pudimos enviar tu confirmación. Por favor intenta de nuevo.",
    guestNotFound: "No encontramos tu nombre en la lista de invitados. Si crees que es un error, contáctanos.",
  },
  faq: {
    heading: "Preguntas Frecuentes",
    items: [
      {
        question: "¿A qué hora debería llegar para la misa y recepción?",
        answer: "Para la misa, por favor llegar entre 11:40 y 11:50 a.m. para que tengas tiempo suficiente de tomar asiento antes que empieze la ceremonia puntualmente a las 12:00 p.m.\nPara la recepción, llegar por favor entre 3:00 y 3:15 p.m. para acomodarse para la boda civil y los votos que empezarán a las 3:30 p.m.",
      },
      {
        question: "¿Cómo confirmo mi asistencia?",
        answer: "Puedes confirmar tu asistencia en la sección 'Confirmar Asistencia' o escribiéndonos por WhatsApp.\n Agradecemos que confirmes hasta el 8 de octubre. Si no recibimos tu confirmación hasta esa fecha, entenderemos que lamentablemente no podrás acompañarnos este día.",
      },
      //{
      //  question: "¿Puedo llevar acompañante?",
      //  answer: "Solo podrán asistir las personas incluidas en la invitación por los cupos asignados. Si tienes dudas, escríbenos por WhatsApp.",
      //},
      {
        question: "¿Es un evento solo para adultos?",
        answer: "Sí, con mucho cariño pedimos que sea una celebración solo para adultos.",
      },
      //{
      //  question: "¿Cuál es el código de vestimenta?",
      //  answer: "Elegante. Caballeros de esmoquin o traje oscuro, damas de vestido largo o cóctel elegante.",
      //},
      {
        question: "¿Habrá estacionamiento?",
        answer: "Sí, ambas locaciones cuentan con estacionamiento disponible para los invitados. En el caso de la iglesia, hay una playa de Apparka en la misma cuadra en la siguiente esquina.",
      },
      {
        question: "¿Cómo funciona la mesa de regalos?",
        answer: "Pueden elegir alguno de los regalos que hemos seleccionado o, si lo prefieren, realizar un aporte libre que destinaremos con mucho cariño a nuestra luna de miel. Una vez elegido el regalo, la web los dirigirá a una plataforma segura, donde podrán completar el proceso con tarjeta de crédito, tarjeta de débito, Yape o Plin.\n\nSi prefieren hacerlo mediante transferencia, pueden realizarlo a las siguientes cuentas a nombre de Gabriel Dejo.\n BCP\n19170142836048\nCCI 00219117014283604853\n\nScotiabank\n833-0064602\nCCI 00972420833006460267\n\nInterbank\n100-3276288960\nCCI 00310001327628896059\n\nLes agradeceremos colocar su nombre en el concepto para poder agradecerles por su detalle.",
      },
    ],
  },
  contact: {
    heading: "¿Tienes alguna duda?",
    lines: [
      "Con gusto te ayudamos con cualquier duda sobre el evento.",
      "Escríbenos directamente por WhatsApp.",
    ],
    whatsappLabel: "Escríbenos",
    whatsappUrl: "https://wa.me/34600000000?text=Hola%20Sol%20%26%20Gabriel!",
  },
  merchant: {
    tradeName: "Mesa de Regalos Sol y Gabriel",
    legalName: "DEJO SEMINARIO GABRIEL FERNANDO",
    taxId: "10729321767",
    phone: "948427924",
    email: "gabrieldejos@gmail.com",
    address: "Jirón Aragón 119, Lima, Perú",
  },
};

export default es;
